spring:
  application:
    name: PET_EYE_SHOP

  # ===============================
  # LOAD ENV FILE
  # ===============================
  config:
    import: optional:file:.env[.properties]

  # ===============================
  # DATABASE (MYSQL)
  # ===============================
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf8
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  # ===============================
  # REDIS CONFIG
  # ===============================
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5000ms
      repositories:
        enabled: false

  # ===============================
  # MAIL CONFIG
  # ===============================
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ===============================
# JWT CONFIG (MAP FROM .env)
# ===============================
jwt:
  signer-key: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

# ===============================
# SERVER
# ===============================
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api


# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: OFF
      springframework:
        web: INFO

# ===============================
# Cloudinary CONFIG (MAP FROM .env)
# ===============================
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# ===============================
# Goong Map CONFIG (MAP FROM .env)
# ===============================
goong:
  api:
    key: ${GOONG_API_KEY}
  geocode:
    url: https://rsapi.goong.io/Geocode
  distance:
    matrix:
      url: https://rsapi.goong.io/DistanceMatrix
